
# mas is for Appstore apps: https://github.com/mas-cli/mas
# mas "1Password", id: 443987910

# brew 'docker'
# brew 'docker-compose' # use docker for mac https://docs.docker.com/v17.09/docker-for-mac/install/

# brew 'postgresql' # install via http://postgresapp.com/
# brew 'pgcli'
brew 'mongodb' # https://www.mongodb.org/downloads#production
brew 'python'
brew 'python3'
brew 'ruby'

brew 'coreutils'
brew 'moreutils'
brew 'findutils'
brew 'gnu-sed', args: ['--with-default-names']

brew 'bash'
brew 'bash-completion'

# generic colouriser  http://kassiopeia.juls.savba.sk/~garabik/software/grc/
# brew 'grc'

# brew 'wget'

# Install more recent versions of some OS X tools
# brew 'vim', args: ['--with-override-system-vi']
brew 'grep'
brew 'openssh'

# z hopping around folders
brew 'z'

# github util. gotta love `hub fork`, `hub create`, `hub checkout <PRurl>`, https://github.com/github/hub
brew 'hub'

# mtr - ping & traceroute.
# brew 'mtr'

    # allow mtr to run without sudo
    # mtrlocation=$(brew info mtr | grep Cellar | sed -e 's/ (.*//')
    #  e.g. `/Users/name/.homebrew/Cellar/mtr/0.86`
    # sudo chmod 4755 $mtrlocation/sbin/mtr
    # sudo chown root $mtrlocation/sbin/mtr


# other useful binaries
brew 'the_silver_searcher'
brew 'fzf'

# brew 'node' # use nvm

brew 'pv'
brew 'rename'
brew 'tree'

brew 'terminal-notifier'

brew 'pidcat'   # colored logcat

brew 'ncdu' # find where your diskspace went

brew 'zsh'

brew 'git-lfs'  # https://git-lfs.github.com/

##
## Cask
##

# tap "caskroom/cask"
brew 'cask'
cask_args appdir: '/Applications'

# brew 'cocoapods'
# cask 'webstorm'
# cask 'java8' # react-native needs this version for android studio to build apk
# cask 'intellij-idea'
# cask 'android-studio'
# mas 'Apple Configurator 2', id: 1037126344
# cask 'fastlane'
# cask 'virtualbox'
# cask 'atom'

cask 'visual-studio-code'
cask 'postico'
cask 'dbeaver-community'
cask 'skype'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'spectacle'
cask 'iterm2'
cask 'postman'

tap 'caskroom/fonts'
cask 'font-fira-code'

# Not on homebrew
# teamsql
# mongodb compass
# openvpn, tunnelblick
# docker
# http://postgresapp.com/

