[git_status]
conflicted = "⚔️ "
ahead = "🏎️ 💨×${count} "
behind = "🐢×${count} "
diverged = "🔱 🏎️ 💨×${ahead_count} 🐢×${behind_count} "
untracked = "🛤️ ×${count} "
stashed = "📦 "
modified = "📝×${count} "
staged = "🗃️ ×${count} "
renamed = "📛×${count} "
deleted = "🗑️ ×${count} "
style = "bright-white"
format = "$all_status$ahead_behind"

[directory]
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = false

[gcloud]
disabled = true

[aws]
disabled = true
